# Generated by Django 5.2.1 on 2025-05-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
    ]
