# Generated by Django 5.2.1 on 2025-05-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_remove_music_description_remove_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='drive_link',
        ),
        migrations.RemoveField(
            model_name='video',
            name='drive_link',
        ),
        migrations.AddField(
            model_name='music',
            name='audio_file',
            field=models.FileField(default=0, upload_to='music/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=2, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
