# Generated by Django 5.2.1 on 2025-05-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0003_remove_music_drive_link_remove_video_drive_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='music',
            name='drive_link',
            field=models.URLField(default=5, verbose_name='Google Drive Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='drive_link',
            field=models.URLField(default=5, verbose_name='Google Drive Link'),
            preserve_default=False,
        ),
    ]
